services:
  renode:
    build: ./tools/renode
    container_name: telemetry-renode
    volumes:
      - ./firmware:/firmware
    ports:
      - '4321:4321'
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: telemetry-backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - RENODE_UART_HOST=renode
    depends_on:
      - renode
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: telemetry-frontend
    ports:
      - '4200:80'
    restart: unless-stopped
